-- Pre-computed report frequencies table
-- Created and populated by python/06_calculate_frequencies.py
-- Note: Reports are now grouped by (proper_title, normalized_body) to separate
-- different UN bodies (GA, ECOSOC, etc.) that may have the same report title

-- Drop and recreate to update schema (data will be regenerated by Python script)
DROP TABLE IF EXISTS sg_reports_survey.report_frequencies;

CREATE TABLE sg_reports_survey.report_frequencies (
  proper_title TEXT NOT NULL,
  normalized_body TEXT NOT NULL DEFAULT '',  -- Normalized UN body (empty string if unknown)
  calculated_frequency TEXT NOT NULL,        -- 'annual', 'biennial', 'one-time', etc.
  gap_history INT[],                         -- [1, 1, 2, 1] for debugging/transparency
  year_count INT,                            -- number of distinct publication years
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (proper_title, normalized_body)
);

-- Index for efficient joins
CREATE INDEX idx_report_frequencies_frequency 
  ON sg_reports_survey.report_frequencies(calculated_frequency);

CREATE INDEX idx_report_frequencies_body
  ON sg_reports_survey.report_frequencies(normalized_body);

-- Comments for documentation
COMMENT ON TABLE sg_reports_survey.report_frequencies IS 'Pre-computed reporting frequencies using weighted mode algorithm, grouped by title and UN body';
COMMENT ON COLUMN sg_reports_survey.report_frequencies.proper_title IS 'Report title for grouping';
COMMENT ON COLUMN sg_reports_survey.report_frequencies.normalized_body IS 'Normalized UN body extracted from un_body field (empty string if unknown)';
COMMENT ON COLUMN sg_reports_survey.report_frequencies.calculated_frequency IS 'Frequency label: annual, biennial, triennial, quadrennial, one-time, etc.';
COMMENT ON COLUMN sg_reports_survey.report_frequencies.gap_history IS 'Array of year gaps between publications (most recent first)';
COMMENT ON COLUMN sg_reports_survey.report_frequencies.year_count IS 'Number of distinct publication years for this report group';
